#!/usr/bin/env python3
"""
dashboard.py - assemble the interactive HTML match report (Deadlock "Brass HUD" skin).

Inputs:
  --digest   path to <id>_digest.json   (from dl_lib / fetch.py)
  --analysis path to analysis.json       (the written analysis; schema in assets/analysis_schema.md)
  --out      output html path             (default <id>_report.html)

If --analysis is omitted the page still renders all data + charts, with the prose sections
showing "analysis pending" so the dashboard is useful even before the LLM pass.

Visual identity: 1930s noir Art Deco - aged brass/gold ornament on deep teal-black, condensed
deco display type (Big Shoulders Display) + clean sans body (Barlow), corner-bracket framing,
patina/vignette overlays, and Deadlock's category colour coding (Weapon amber / Vitality green /
Spirit violet, souls cyan). Real hero portraits and item icons resolve from the assets API at
digest-build time (dl_lib carries the URLs); each item slot degrades to a styled placeholder when
no icon URL is available. Charts are generated by charts.py with a matching palette; plotly.js is
loaded once via CDN.
"""
import argparse, html, json, re, sys
from pathlib import Path
from urllib.parse import urlsplit
sys.path.insert(0, str(Path(__file__).resolve().parent))
import charts as C

PHASES = ["Laning", "Early-mid", "Mid", "Late"]
CATS = ["Economy", "Combat", "Survivability", "Itemisation", "Targeting", "Macro"]

# category -> css class used for item chips / split pips
SLOT_CLASS = {"weapon": "weapon", "spirit": "spirit", "vitality": "vitality"}

CSS = """
*{box-sizing:border-box}
html,body{margin:0}
body{background:#0a0d13;color:#e8e0cf;font-family:'Barlow',system-ui,sans-serif;line-height:1.5}
a{text-decoration:none}
::selection{background:#C8A24A55}
.disp{font-family:'Big Shoulders Display',sans-serif}
.cond{font-family:'Barlow Semi Condensed',sans-serif}
.brass-text{background:linear-gradient(180deg,#F4D888,#C8A24A 60%,#7d6128);-webkit-background-clip:text;background-clip:text;color:transparent}
.tex{position:fixed;inset:0;pointer-events:none;z-index:1;opacity:.045;mix-blend-mode:overlay;background-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='180' height='180'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='2' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E");background-size:180px 180px}
.vig{position:fixed;inset:0;pointer-events:none;z-index:1;background:radial-gradient(120% 80% at 50% -10%,#15243033,transparent 60%),radial-gradient(100% 60% at 50% 120%,#1a140833,transparent 60%)}
header.site{position:sticky;top:0;z-index:20;background:rgba(10,13,19,.93);backdrop-filter:blur(9px);border-bottom:1px solid #6c552a55}
.hwrap{max-width:1100px;margin:0 auto;padding:13px 26px}
.hrow{display:flex;align-items:baseline;gap:13px;flex-wrap:wrap}
.heroname{font-family:'Big Shoulders Display',sans-serif;font-weight:800;font-size:27px;letter-spacing:.04em;line-height:1}
.result{font-family:'Big Shoulders Display',sans-serif;font-weight:600;font-size:12px;letter-spacing:.3em;text-transform:uppercase}
.result.loss{color:#C04A3C}.result.win{color:#6FA84B}
.metaline{color:#a89f8a;font-size:14px;letter-spacing:.03em}
.metaline .souls{color:#2ADFFC}.metaline .mid{color:#847c6a}
.homelink{display:inline-block;font-family:'Barlow Semi Condensed',sans-serif;font-weight:600;font-size:12px;letter-spacing:.1em;text-transform:uppercase;color:#9a7b3d;margin-bottom:8px}
.homelink:hover{color:#C8A24A}
nav{display:flex;gap:6px;flex-wrap:wrap;margin-top:11px}
nav a{font-family:'Barlow Semi Condensed',sans-serif;font-weight:600;font-size:12.5px;letter-spacing:.1em;text-transform:uppercase;color:#a89f8a;padding:4px 11px;border:1px solid #2a3144;background:#11151d}
nav a:hover{color:#e8e0cf;border-color:#C8A24A}
main{position:relative;z-index:2;max-width:1100px;margin:0 auto;padding:0 26px 70px}
section{padding:34px 0 8px}
section.divided{border-top:1px solid #1c2231;margin-top:30px}
.sec-head{display:flex;align-items:center;gap:12px;margin-bottom:16px}
.sec-title{font-family:'Big Shoulders Display',sans-serif;font-weight:800;font-size:22px;letter-spacing:.06em;color:#e8e0cf;margin:0;text-transform:uppercase}
.rule{flex:1;height:2px;background:linear-gradient(90deg,#C8A24A,#C8A24A22 60%,transparent)}
.dia{color:#7d6128}
.eyebrow{font-family:'Barlow Semi Condensed',sans-serif;font-weight:600;font-size:12px;letter-spacing:.28em;color:#9a7b3d;text-transform:uppercase}
.ovhead{display:flex;align-items:center;gap:14px;margin-bottom:16px}
h1.title{font-family:'Big Shoulders Display',sans-serif;font-weight:800;font-size:58px;line-height:.84;letter-spacing:.02em;margin:4px 0 0}
.subtitle{margin-top:8px;color:#a89f8a;font-size:19.5px;letter-spacing:.03em;font-weight:700}
.portrait{width:90px;height:112px;flex:0 0 auto;border:1px solid #6c552a;box-shadow:inset 0 0 0 1px #00000080,0 6px 18px #00000066;background:#0b0e14;overflow:hidden;position:relative}
.portrait img{width:100%;height:100%;object-fit:cover;object-position:center top;filter:saturate(.92) contrast(1.03)}
.portrait .fade{position:absolute;inset:0;background:linear-gradient(180deg,transparent 55%,#0a0d13cc)}
.statstrip{display:grid;grid-template-columns:repeat(6,1fr);gap:8px;margin:18px 0 20px}
.stat{background:linear-gradient(180deg,#1b2130,#11151e);border:1px solid #2a3144;border-top:2px solid #C8A24A;padding:10px 12px}
.stat .k{font-size:11.5px;letter-spacing:.1em;color:#978d77;text-transform:uppercase;font-weight:700}
.stat .v{font-family:'Big Shoulders Display',sans-serif;font-weight:700;font-size:24px;color:#e8e0cf}
.bracket{position:relative;background:linear-gradient(180deg,#141925,#0e121b);border:1px solid #6c552a55;box-shadow:inset 0 0 0 1px #2a2f3d;padding:22px 24px;overflow:hidden}
.bracket .c{position:absolute;width:15px;height:15px;opacity:.8}
.bracket .tl{top:7px;left:7px;border-top:2px solid #C8A24A;border-left:2px solid #C8A24A}
.bracket .tr{top:7px;right:7px;border-top:2px solid #C8A24A;border-right:2px solid #C8A24A}
.bracket .bl{bottom:7px;left:7px;border-bottom:2px solid #C8A24A;border-left:2px solid #C8A24A}
.bracket .br{bottom:7px;right:7px;border-bottom:2px solid #C8A24A;border-right:2px solid #C8A24A}
.verdict{color:#d4cdba;font-size:16.5px;line-height:1.75;max-width:980px}
.prio{list-style:none;padding:0;margin:12px 0 0}
.prio li{position:relative;padding:14px 16px 14px 56px;background:#11151d;border:1px solid #232a3a;border-left:3px solid #C8A24A;margin:9px 0;color:#d4cdba;font-size:15.5px;line-height:1.65}
.prio li .n{position:absolute;left:14px;top:14px;width:28px;height:28px;display:grid;place-items:center;font-family:'Big Shoulders Display',sans-serif;font-weight:800;font-size:16px;color:#0a0d13;background:linear-gradient(180deg,#F4D888,#C8A24A)}
.chartpanel{background:linear-gradient(180deg,#141925,#0e121b);border:1px solid #232a3a;border-top:2px solid #C8A24A;padding:14px 16px 6px;margin-top:12px}
.chart-title{font-family:'Big Shoulders Display',sans-serif;font-weight:700;font-size:14px;letter-spacing:.06em;color:#C8A24A;text-transform:uppercase;margin-bottom:2px}
.chart-sub{font-size:12.5px;color:#978d77;letter-spacing:.05em;margin-bottom:6px}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:12px}
.phase-head{display:flex;align-items:baseline;gap:13px;margin-bottom:4px}
.phase-title{font-family:'Big Shoulders Display',sans-serif;font-weight:800;font-size:30px;letter-spacing:.05em;color:#e8e0cf;margin:0;text-transform:uppercase}
.phase-win{font-family:'Barlow Semi Condensed',sans-serif;font-size:13px;letter-spacing:.14em;color:#9a7b3d;text-transform:uppercase}
.phase-sum{color:#cabd9f;font-size:16px;font-style:italic;margin:6px 0 14px;max-width:900px}
.chips{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px}
.chip{background:#11151d;border:1px solid #2a3144;border-top:2px solid #C8A24A;padding:8px 13px;min-width:92px}
.chip .k{font-size:11.5px;letter-spacing:.1em;color:#978d77;text-transform:uppercase;font-weight:700}
.chip .v{font-family:'Big Shoulders Display',sans-serif;font-weight:700;font-size:20px;color:#e8e0cf}
.cat{border:1px solid #232a3a;background:#11151d;margin:9px 0}
.cat-h{padding:11px 16px;font-family:'Big Shoulders Display',sans-serif;font-weight:700;font-size:16.5px;letter-spacing:.07em;text-transform:uppercase;color:#C8A24A;background:linear-gradient(180deg,#1b2130,#141925);border-bottom:1px solid #232a3a}
.cat-h .dia{margin-right:8px}
.cat-b{padding:8px 16px 14px}
.buck{display:flex;gap:10px;margin:8px 0}
.buck .lbl{flex:0 0 auto;align-self:flex-start;font:700 11px 'Barlow Semi Condensed',sans-serif;letter-spacing:.08em;text-transform:uppercase;padding:3px 8px}
.buck .txt{color:#cfc7b4;font-size:15px;line-height:1.6}
.buck.blind .txt{color:#b3aa93;font-style:italic}
.lbl.good{color:#6FA84B;background:#6FA84B1f;border:1px solid #6FA84B55}
.lbl.mid{color:#D9A441;background:#D9A4411f;border:1px solid #D9A44155}
.lbl.bad{color:#e07a75;background:#C8413B1f;border:1px solid #C8413B55}
.lbl.blind{color:#8b93a7;background:#8b93a71a;border:1px solid #8b93a744}
.subhead{font-family:'Big Shoulders Display',sans-serif;font-weight:700;font-size:15px;letter-spacing:.08em;color:#C8A24A;text-transform:uppercase;margin:22px 0 10px}
.itemrow{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}
.item{display:flex;align-items:center;gap:10px;background:linear-gradient(90deg,#16140f,#11151e);border:1px solid #2a3144;padding:8px 12px}
.item .ico{flex:0 0 auto;border:1px solid #2a3144;display:grid;place-items:center;overflow:hidden}
.item .ico img{width:100%;height:100%;object-fit:contain}
.item .nm{font-family:'Big Shoulders Display',sans-serif;font-weight:600;color:#e8e0cf;line-height:1.05}
.item .sub{letter-spacing:.09em;text-transform:uppercase}
.item.weapon{border-left:3px solid #C56B2C}
.item.weapon .ico{background:linear-gradient(160deg,#a8642a,#5e3414);border-color:#C56B2C}
.item.weapon .sub{color:#C56B2C}
.item.spirit{border-left:3px solid #B07BD6}
.item.spirit .ico{background:linear-gradient(160deg,#5a3a6a,#371a44);border-color:#B07BD6}
.item.spirit .sub{color:#B07BD6}
.item.vitality{border-left:3px solid #6FA84B}
.item.vitality .ico{background:linear-gradient(160deg,#3c5a2a,#24371a);border-color:#6FA84B}
.item.vitality .sub{color:#6FA84B}
.item.other{border-left:3px solid #C8A24A}
.item.other .ico{background:linear-gradient(160deg,#5a4a26,#2e2410);border-color:#C8A24A}
.item.other .sub{color:#C8A24A}
.tgt-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:20px}
.tgt-h{font-family:'Big Shoulders Display',sans-serif;font-weight:700;font-size:13px;letter-spacing:.08em;text-transform:uppercase;margin-bottom:8px}
.tgt-h.good{color:#6FA84B}.tgt-h.bad{color:#C8413B}
.bar{display:flex;align-items:center;gap:9px;margin:6px 0}
.bar .nm{width:84px;color:#cabd9f;font-size:13.5px}
.bar .track{flex:1;height:14px;background:#1b2130;position:relative;overflow:hidden}
.bar .fill{position:absolute;left:0;top:0;bottom:0}
.bar .val{width:54px;text-align:right;font-family:'Big Shoulders Display',sans-serif;color:#e8e0cf;font-size:14.5px}
.sdpanel{margin-top:16px;background:#16140f;border:1px solid #3a2c16;border-left:3px solid #D9A441;padding:11px 14px}
.sdhead{display:flex;align-items:baseline;gap:9px;flex-wrap:wrap}
.sdhead .k{font-family:'Barlow Semi Condensed',sans-serif;font-weight:600;font-size:11px;letter-spacing:.12em;color:#D9A441;text-transform:uppercase}
.sdhead .v{font-family:'Big Shoulders Display',sans-serif;font-weight:700;font-size:22px;color:#D9A441}
.sdhead .sdsub{color:#978d77;font-size:12px;letter-spacing:.02em}.sdhead .sdsub b{color:#cabd9f}
.sdlist{display:flex;flex-wrap:wrap;gap:6px 8px;margin-top:9px}
.sdrow{display:inline-flex;align-items:center;gap:6px;background:#11151d;border:1px solid #2a3144;padding:4px 9px;font-size:12.5px}
.sdrow .sn{color:#cabd9f}.sdrow .sv{font-family:'Big Shoulders Display',sans-serif;color:#D9A441;font-weight:700}
.cards3{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px}
.ecard{background:#11151d;border:1px solid #232a3a;border-top:2px solid #C8413B;padding:13px 15px}
.ecard .h{font-family:'Big Shoulders Display',sans-serif;font-weight:700;font-size:18px;color:#e8e0cf;letter-spacing:.03em}
.ecard .k{font-size:11px;color:#C8413B;letter-spacing:.08em;text-transform:uppercase;margin:2px 0 7px}
.ecard .t{color:#b3aa93;font-size:14px;line-height:1.55}
.note{font-size:12px;color:#847c6a;font-style:italic;margin-top:9px}
.sbwrap{background:linear-gradient(180deg,#141925,#0e121b);border:1px solid #232a3a;overflow:hidden}
table.sb{width:100%;border-collapse:collapse;font-size:14px}
table.sb th{text-align:left;padding:10px 14px;color:#978d77;font-family:'Barlow Semi Condensed',sans-serif;font-weight:700;font-size:12px;letter-spacing:.08em;text-transform:uppercase}
table.sb th.r{text-align:right}
.sb td{padding:9px 14px;color:#cdc6b3}
.sb td.r{text-align:right}
.sb td.kda{color:#bcae92}
.sb td.nw{text-align:right;font-family:'Big Shoulders Display',sans-serif;color:#e8e0cf}
.sb td.mut{color:#a89f8a}
.sb tr.row{border-bottom:1px solid #1c2231}
.sb tr.you{background:rgba(200,162,74,.09);box-shadow:inset 3px 0 0 #C8A24A}
.sb tr.you td{color:#e8e0cf}
.sb tr.you td.name{color:#F4D888;font-weight:700}
.sb tr.you td.nw{color:#F4D888;font-weight:700}
.sb .teamhead td{padding:8px 14px;font-family:'Big Shoulders Display',sans-serif;font-weight:700;font-size:13px;letter-spacing:.12em;text-transform:uppercase;border-top:1px solid #232a3a;border-bottom:1px solid #232a3a}
.sb .teamhead.lost td{background:#160f0d;color:#C8413B}
.sb .teamhead.won td{background:#0c1612;color:#6FA84B}
.youtag{font-family:'Barlow Semi Condensed',sans-serif;font-weight:600;font-size:11px;letter-spacing:.08em;color:#C8A24A;border:1px solid #C8A24A66;padding:1px 6px;margin-left:4px;text-transform:uppercase}
.kotag{font-family:'Barlow Semi Condensed',sans-serif;font-size:11px;letter-spacing:.05em;color:#C8413B;border:1px solid #C8413B66;padding:1px 5px;text-transform:uppercase;margin-left:6px}
.wsv .w{color:#C56B2C}.wsv .s{color:#B07BD6}.wsv .v{color:#6FA84B}
.pending{color:#978d77;font-style:italic}
.footer{margin-top:30px;padding-top:18px;border-top:1px solid #1c2231;color:#7a7160;font-size:13px;letter-spacing:.04em;text-align:center}
.footer b{color:#978d77}
/* inline rich text: item icons + hero avatars embedded in prose */
.rich{display:inline-flex;align-items:center;gap:4px;white-space:nowrap;vertical-align:baseline}
.rich .ava{width:18px;height:18px;border-radius:50%;object-fit:cover;object-position:center top;border:1px solid #6c552a;flex:0 0 auto}
.rich .iico{width:18px;height:18px;object-fit:contain;border-radius:3px;background:#0b0e14;flex:0 0 auto}
/* header / row / bar avatars */
.hava{width:24px;height:24px;border-radius:50%;object-fit:cover;object-position:center top;border:1px solid #6c552a;vertical-align:middle;margin-right:8px}
.sbava{width:22px;height:22px;border-radius:50%;object-fit:cover;object-position:center top;border:1px solid #2a3144;vertical-align:middle;margin-right:9px}
.bar .nm{display:inline-flex;align-items:center;gap:7px;width:108px}
.baravatar{width:18px;height:18px;border-radius:50%;object-fit:cover;object-position:center top;border:1px solid #2a3144;flex:0 0 auto}
.ecard .h{display:flex;align-items:center}
/* deaths map + timeline */
.mapwrap{position:relative;width:100%;max-width:560px;margin:6px auto 0;aspect-ratio:1/1;border:1px solid #2a3144;background:#0b0e14;overflow:hidden}
.mapimg{position:absolute;inset:0;width:100%;height:100%;object-fit:contain;opacity:.92}
.ganksvg{position:absolute;inset:0;width:100%;height:100%;pointer-events:none}
.ganksvg line{stroke:#C8413B;stroke-width:.5;stroke-dasharray:1.6 1.2;opacity:.6}
.mlayer{position:absolute;inset:0}
.dmark{position:absolute;transform:translate(-50%,-50%);display:grid;place-items:center;font-family:'Big Shoulders Display',sans-serif;font-weight:800;color:#0a0d13;cursor:default}
.dmark.death{width:19px;height:19px;font-size:11px;border-radius:50%;background:#C8413B;border:1.5px solid #f0c0bc;box-shadow:0 1px 4px #000a}
.dmark.kill{width:11px;height:11px;border-radius:50%;background:#C8A24A;border:1px solid #f4d888;box-shadow:0 1px 3px #0008}
.maplegend{display:flex;gap:18px;justify-content:center;margin-top:12px;font-size:12.5px;color:#a89f8a;letter-spacing:.04em}
.maplegend .lg{display:inline-flex;align-items:center;gap:6px}
.maplegend .lg::before{content:"";width:11px;height:11px;border-radius:50%;display:inline-block}
.maplegend .death::before{background:#C8413B}
.maplegend .kill::before{background:#C8A24A}
.maplegend .line::before{border-radius:0;width:15px;height:0;border-top:2px dashed #C8413B}
.dtl{display:flex;flex-direction:column;gap:8px;margin-top:10px}
.dtl-card{display:flex;gap:12px;background:#11151d;border:1px solid #232a3a;border-left:3px solid #C8413B;padding:11px 14px}
.dtl-n{flex:0 0 auto;width:24px;height:24px;border-radius:50%;background:#C8413B;color:#0a0d13;font-family:'Big Shoulders Display',sans-serif;font-weight:800;display:grid;place-items:center;font-size:14px}
.dtl-main{flex:1;min-width:0}
.dtl-h{color:#e8e0cf;font-size:15px;display:flex;align-items:center;gap:6px;flex-wrap:wrap}
.dtl-h .dtl-t{color:#978d77;font-size:12.5px;letter-spacing:.04em;margin-left:auto}
.dtl-meta{color:#a89f8a;font-size:12.5px;margin-top:3px}
.dtl-dmg{margin-top:7px;display:flex;gap:6px 12px;flex-wrap:wrap;align-items:center}
.dtl-dmg .dlabel{color:#847c6a;font-size:11px;text-transform:uppercase;letter-spacing:.06em}
.dsrc{display:inline-flex;align-items:center;gap:4px;color:#cabd9f;font-size:12.5px;white-space:nowrap}
.dsrc img{width:16px;height:16px}
@media(max-width:760px){.mapwrap{max-width:100%}}
/* hero playbook: situational tips, macro, resources */
.sitgrid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:10px}
.sitcard{background:#11151d;border:1px solid #232a3a;border-top:2px solid #C8A24A;padding:13px 15px}
.sit-h{font-family:'Big Shoulders Display',sans-serif;font-weight:700;font-size:15px;letter-spacing:.04em;color:#C8A24A;text-transform:uppercase;margin-bottom:6px}
.sit-b{color:#cfc7b4;font-size:14.5px;line-height:1.6}
.tips{list-style:none;padding:0;margin:10px 0 0}
.tips li{position:relative;padding:11px 14px 11px 30px;background:#11151d;border:1px solid #232a3a;border-left:3px solid #6FA84B;margin:8px 0;color:#d4cdba;font-size:15px;line-height:1.6}
.tips li::before{content:"◆";position:absolute;left:11px;top:12px;color:#6FA84B;font-size:11px}
.reslist{display:flex;flex-direction:column;gap:8px;margin-top:10px}
a.res{display:grid;grid-template-columns:auto 1fr auto;gap:2px 14px;align-items:center;background:linear-gradient(90deg,#16140f,#11151e);border:1px solid #2a3144;border-left:3px solid #2ADFFC;padding:11px 15px}
a.res:hover{border-color:#2ADFFC;background:linear-gradient(90deg,#1a1812,#141a26)}
.res .rk{grid-column:1;grid-row:1/3;align-self:center;font-family:'Barlow Semi Condensed',sans-serif;font-weight:700;font-size:12px;letter-spacing:.05em;color:#2ADFFC;text-transform:uppercase;min-width:62px}
.res .rt{grid-column:2;grid-row:1;font-family:'Big Shoulders Display',sans-serif;font-weight:700;font-size:16px;color:#e8e0cf;letter-spacing:.02em}
.res .rwhy{grid-column:2;grid-row:2;color:#a89f8a;font-size:13px;line-height:1.45}
.res .rhost{grid-column:3;grid-row:1/3;align-self:center;color:#7a7160;font-size:12px;white-space:nowrap}
@media(max-width:760px){.sitgrid{grid-template-columns:1fr}.res .rhost{display:none}}
/* builds + deadlock UI item cards */
.buildrow{display:flex;flex-wrap:wrap;gap:8px;align-items:flex-start;margin-top:10px}
.buildrow dl-item-card{display:block}
.cardico{flex:0 0 auto;display:flex}
.cardico dl-item-card{display:block}
details.cat>summary{cursor:pointer;list-style:none}
details.cat>summary::-webkit-details-marker{display:none}
details.cat>summary .dia{color:#7d6128}
details.cat[open]>summary.cat-h{border-bottom:1px solid #232a3a}
@media(max-width:760px){.statstrip{grid-template-columns:repeat(3,1fr)}.grid2,.tgt-grid,.cards3{grid-template-columns:1fr}h1.title{font-size:42px}}
"""


def esc(s):
    return html.escape(str(s))


def c(n):
    try:
        return f"{int(n):,}"
    except (TypeError, ValueError):
        return str(n)


def k(n):
    """Compact souls/damage: 36668 -> 36.7k, 956 -> 956."""
    try:
        n = float(n)
    except (TypeError, ValueError):
        return str(n)
    return f"{n/1000:.1f}k" if abs(n) >= 1000 else f"{int(n)}"


def natjoin(xs):
    xs = list(xs)
    if not xs:
        return ""
    if len(xs) == 1:
        return xs[0]
    return ", ".join(xs[:-1]) + " & " + xs[-1]


# ---- small components -------------------------------------------------------
def sec_head(title):
    return (f'<div class="sec-head"><h2 class="sec-title">{esc(title)}</h2>'
            f'<span class="rule"></span><span class="dia">◆</span></div>')


def brackets():
    return ('<span class="c tl"></span><span class="c tr"></span>'
            '<span class="c bl"></span><span class="c br"></span>')


def stat(kk, vv, accent="#C8A24A", vcolor="#e8e0cf"):
    return (f'<div class="stat" style="border-top-color:{accent}">'
            f'<div class="k">{esc(kk)}</div>'
            f'<div class="v" style="color:{vcolor}">{esc(vv)}</div></div>')


def chip(kk, vv, accent="#C8A24A", vcolor="#e8e0cf"):
    return (f'<div class="chip" style="border-top-color:{accent}">'
            f'<div class="k">{esc(kk)}</div>'
            f'<div class="v" style="color:{vcolor}">{esc(vv)}</div></div>')


def _shape(cls):
    if cls == "weapon":
        return '<div style="width:46%;height:16%;background:#f0c79a;transform:rotate(-22deg)"></div>'
    if cls == "spirit":
        return '<div style="width:42%;height:42%;border:2px solid #e0c0f5;border-radius:50%"></div>'
    if cls == "vitality":
        return '<div style="width:44%;height:44%;border:2px solid #b6e09a;border-radius:2px;transform:rotate(45deg)"></div>'
    return '<div style="width:42%;height:42%;border:2px solid #f4d888;transform:rotate(45deg)"></div>'


def item_card(iid, name):
    """Official Deadlock UI item card (web component); needs a <dl-provider> ancestor."""
    return f'<dl-item-card item-id="{esc(iid)}" data-name="{esc(name)}"></dl-item-card>'


def _norm_item(s):
    """Loose key for matching a written item name to the asset catalog: lowercase,
    drop an '(imbued)' suffix, normalise British spellings, drop the stale 'improved'
    qualifier (e.g. 'Improved Spirit Armour' -> 'Spirit Armor'), strip non-alphanumerics."""
    s = (s or "").lower()
    s = re.sub(r"\(\s*imbued\s*\)", "", s)
    s = s.replace("armour", "armor").replace("colour", "color")
    s = re.sub(r"\bimproved\b", "", s)
    return re.sub(r"[^a-z0-9]", "", s)


def resolve_item_meta(name, item_index):
    """item_index lookup with a normalised fallback so e.g. 'Improved Spirit Armour'
    still resolves to 'Improved Spirit Armor' (and thus to a card)."""
    meta = item_index.get(name)
    if meta:
        return meta
    cache = resolve_item_meta._cache
    norm = cache.get(id(item_index))
    if norm is None:
        norm = {}
        for nm, m in item_index.items():
            norm.setdefault(_norm_item(nm), m)
        cache[id(item_index)] = norm
    return norm.get(_norm_item(name), {})
resolve_item_meta._cache = {}


# ---- rich inline text: auto-embed item icons & hero avatars in prose --------
GENERIC_ITEM_WORDS = {"health"}  # too generic to auto-link as an item

def _avatar(img, cls="ava", alt=""):
    return f'<img class="{cls}" src="{esc(img)}" alt="{esc(alt)}">' if img else ""


def _richmaps(digest):
    """Build (heroes, items, pattern) for inlining names in prose. Cached per digest.
    Heroes (proper nouns) always link; items link only when distinctive (multi-word or
    >=8 chars) to avoid catching generic words like 'health' in normal sentences."""
    cache = _richmaps._cache
    key = id(digest)
    if key in cache:
        return cache[key]
    heroes = {p["hero"]: p.get("hero_image") for p in digest.get("players", []) if p.get("hero")}
    items = {}
    for name, meta in (digest.get("item_index") or {}).items():
        if not name or not meta.get("id"):
            continue
        if name.lower() in GENERIC_ITEM_WORDS:
            continue
        if (" " in name) or len(name) >= 8:
            items[name] = (meta["id"], meta.get("image"))
    names = sorted(set(heroes) | set(items), key=len, reverse=True)
    # match exact (case-sensitive) names on word-ish boundaries that allow apostrophes
    pattern = (re.compile(r"(?<![\w'])(" + "|".join(re.escape(n) for n in names) + r")(?![\w'])")
               if names else None)
    out = (heroes, items, pattern)
    cache[key] = out
    return out
_richmaps._cache = {}


def hero_inline(name, img):
    return f'<span class="rich">{_avatar(img, "ava", name)}{esc(name)}</span>'


def item_inline(name, img):
    ico = f'<img class="iico" src="{esc(img)}" alt="">' if img else ""
    return f'<span class="rich" title="{esc(name)}">{ico}{esc(name)}</span>'


def rich(text, digest):
    """Escape prose, but replace recognised item / hero names with an inline icon + name."""
    if not text:
        return ""
    heroes, items, pattern = _richmaps(digest)
    if not pattern:
        return esc(text)
    out, last = [], 0
    for m in pattern.finditer(text):
        out.append(esc(text[last:m.start()]))
        name = m.group(1)
        if name in items:
            out.append(item_inline(name, items[name][1]))
        elif name in heroes:
            out.append(hero_inline(name, heroes[name]))
        else:
            out.append(esc(name))
        last = m.end()
    out.append(esc(text[last:]))
    return "".join(out)


def item_chip(name, slot, image, sub, why=None, size=30, iid=None):
    cls = SLOT_CLASS.get((slot or "").lower(), "other")
    nm_size = "15px" if size >= 36 else ("14px" if size >= 34 else "13px")
    sub_size = "11.5px" if size >= 36 else ("11px" if size >= 34 else "10.5px")
    title = f' title="{esc(why)}"' if why else ""
    if iid:
        ico = f'<div class="cardico">{item_card(iid, name)}</div>'
    else:
        inner = f'<img src="{esc(image)}" alt="">' if image else _shape(cls)
        ico = f'<div class="ico" style="width:{size+8}px;height:{size+8}px">{inner}</div>'
    return (f'<div class="item {cls}"{title}>'
            f'{ico}'
            f'<div><div class="nm" style="font-size:{nm_size}">{esc(name)}</div>'
            f'<div class="sub" style="font-size:{sub_size}">{esc(sub)}</div></div></div>')


# ---- overview ---------------------------------------------------------------
def me_totals(me):
    dd = me.get("dmg_series_dealt"); dt = me.get("dmg_series_taken")
    phases = me.get("phases", {})
    hero_dmg = dd[-1][1] if dd else sum(p.get("player_damage", 0) for p in phases.values())
    dmg_taken = dt[-1][1] if dt else sum(p.get("player_damage_taken", 0) for p in phases.values())
    return hero_dmg, dmg_taken


def overview(digest, me, analysis):
    result = "Victory" if digest["i_won"] else "Defeat"
    kk, dd, aa = me["kda"]
    hero_dmg, dmg_taken = me_totals(me)
    self_dmg = me.get("self_damage", 0)
    if me.get("hero_image"):
        portrait = (f'<div class="portrait"><img src="{esc(me["hero_image"])}" alt="{esc(me["hero"])}">'
                    f'<div class="fade"></div></div>')
    else:
        portrait = '<div class="portrait"></div>'
    subtitle = (f'{esc(digest["duration"])} · You went {kk} / {dd} / {aa} · {c(me["net_worth"])} souls'
                + (f' · beaten mainly by {esc(natjoin(digest.get("focus_enemies", [])))}'
                   if digest.get("focus_enemies") else ''))

    strip = "".join([
        stat("Souls/min", c(me["souls_per_min"])),
        stat("Deaths", dd, "#C8413B", "#C8413B"),
        stat("Net worth", k(me["net_worth"]), "#2ADFFC"),
        stat("Hero dmg", k(hero_dmg)),
        stat("Dmg taken", k(dmg_taken), "#C8413B"),
        stat("Self-dmg", k(self_dmg), "#D9A441", "#D9A441"),
    ])

    ov = (analysis or {}).get("overall", {})
    verdict = ov.get("verdict", "")
    verdict_html = (f'<div class="verdict">{rich(verdict, digest)}</div>' if verdict
                    else '<div class="verdict pending">Analysis pending.</div>')
    prios = ov.get("priorities", [])
    prio_html = ""
    if prios:
        items = "".join(f'<li><span class="n">{i+1}</span>{rich(p, digest)}</li>' for i, p in enumerate(prios))
        prio_html = (f'<div class="sec-head" style="margin:26px 0 4px">'
                     f'<h2 class="sec-title">Top priorities next game</h2>'
                     f'<span class="rule"></span><span class="dia">◆</span></div>'
                     f'<ol class="prio">{items}</ol>')

    return f'''<section id="overview">
      <div class="ovhead">{portrait}
        <div style="flex:1;min-width:0">
          <div class="eyebrow">Match Report</div>
          <h1 class="title brass-text">{esc(me["hero"])} — {esc(result)}</h1>
          <div class="subtitle">{subtitle}</div>
        </div>
      </div>
      <div class="statstrip">{strip}</div>
      <div class="bracket">{brackets()}{verdict_html}</div>
      {prio_html}
    </section>'''


# ---- charts -----------------------------------------------------------------
def chart_panel(title, div, sub=None):
    s = f'<div class="chart-sub">{esc(sub)}</div>' if sub else ""
    return f'<div class="chartpanel"><div class="chart-title">{esc(title)}</div>{s}{div}</div>'


def charts_section(ch):
    return f'''<section id="charts" class="divided">
      {sec_head("The game at a glance")}
      {chart_panel("Soul lead over time", ch["soul_lead"], "Dotted red = your deaths · green = mid-boss claimed")}
      <div class="grid2">
        {chart_panel("Net worth · all players", ch["networth_all"])}
        {chart_panel("Your damage · dealt vs taken", ch["dmg_over_time"])}
      </div>
      {chart_panel("Death cost · seconds spent dead", ch["death_cost"])}
      <div class="grid2">
        {chart_panel("Souls by source · per phase", ch["economy_sources"])}
        {chart_panel("Accuracy · per phase", ch["accuracy_phases"])}
      </div>
      {chart_panel("Targeting · damage among you & your killers", ch["targeting_heatmap"])}
    </section>'''


# ---- phases -----------------------------------------------------------------
def phase_chips(seg):
    if not seg:
        return ""
    spm = seg.get("souls_per_min", 0)
    kk = seg.get("kills", 0)
    dd = seg.get("deaths_actual", seg.get("deaths", 0))
    aa = seg.get("assists", 0)
    dmg = seg.get("player_damage", 0)
    taken = seg.get("player_damage_taken", 0)
    acc = seg.get("accuracy_pct")
    return '<div class="chips">' + "".join([
        chip("Souls/min", c(spm), "#6FA84B" if spm >= 1000 else "#C8A24A",
             "#6FA84B" if spm >= 1000 else "#e8e0cf"),
        chip("Souls", f'+{c(seg.get("net_worth", 0))}'),
        chip("K/D/A", f"{kk}/{dd}/{aa}", "#C8413B" if dd > kk else "#C8A24A",
             "#C8413B" if dd > kk else "#e8e0cf"),
        chip("Hero dmg", c(dmg), "#6FA84B" if dmg >= taken else "#C8413B",
             "#6FA84B" if dmg >= taken else "#e8e0cf"),
        chip("Dmg taken", c(taken), "#C8413B", "#C8413B" if taken > dmg else "#e8e0cf"),
        chip("Accuracy", f"{acc}%" if acc is not None else "-", "#D9A441"),
    ]) + "</div>"


def buckets(data, digest):
    rows = ""
    for key, label, cls in [("did_well", "Did well", "good"), ("hard_to_say", "Hard to say", "mid"),
                            ("cost_you", "Cost you", "bad"), ("blind_spots", "Blind spot", "blind")]:
        val = data.get(key)
        if not val:
            continue
        for it in (val if isinstance(val, list) else [val]):
            blind = " blind" if cls == "blind" else ""
            rows += (f'<div class="buck{blind}"><span class="lbl {cls}">{label}</span>'
                     f'<span class="txt">{rich(it, digest)}</span></div>')
    return rows


def category_block(name, data, digest):
    return (f'<div class="cat"><div class="cat-h"><span class="dia">◆</span>{esc(name)}</div>'
            f'<div class="cat-b">{buckets(data, digest) or "<p class=pending>No notes.</p>"}</div></div>')


def suggestion_chips(sgs, item_index, label="Items that would have helped here", size=30):
    if not sgs:
        return ""
    chips = ""
    for s in sgs:
        name = s.get("item", "")
        meta = resolve_item_meta(name, item_index)
        slot = meta.get("slot")
        cat = (slot.title() + " · ") if slot else ""
        tail = ("instead of " + s["instead_of"]) if s.get("instead_of") else "suggested"
        chips += item_chip(name, slot, meta.get("image"), cat + tail, why=s.get("why"),
                           size=size, iid=meta.get("id"))
    return f'<div class="subhead">{esc(label)}</div><div class="itemrow">{chips}</div>'


def phase_section(phase, digest, analysis, item_index):
    me = next(p for p in digest["players"] if p["is_me"])
    seg = me.get("phases", {}).get(phase, {})
    a = (analysis or {}).get("phases", {}).get(phase, {})
    head = a.get("summary", "")
    win = seg.get("window", "")
    cats = a.get("categories", {})
    body = "".join(category_block(cn, cats[cn], digest) for cn in CATS if cats.get(cn))
    if not body:
        body = '<p class="pending">Analysis pending for this phase.</p>'
    sug = suggestion_chips(a.get("item_suggestions"), item_index)
    return f'''<section id="{phase.lower().replace(" ", "-")}" class="divided">
      <div class="phase-head">
        <h2 class="phase-title">{esc(phase)}</h2>
        <span class="phase-win">{esc(win)}</span>
        <span class="rule"></span>
      </div>
      {f'<p class="phase-sum">{rich(head, digest)}</p>' if head else ''}
      {phase_chips(seg)}{body}{sug}
    </section>'''


# ---- targeting --------------------------------------------------------------
def dmg_bars(d, kind, himg=None):
    if not d:
        return '<p class="pending">No data.</p>'
    himg = himg or {}
    items = list(d.items())[:6]
    mx = max(v for _, v in items) or 1
    grad = ("linear-gradient(90deg,#6FA84B,#3c5a2a)" if kind == "good"
            else "linear-gradient(90deg,#C8413B,#5e1814)")
    rows = ""
    for hero, v in items:
        w = round(100 * v / mx)
        rows += (f'<div class="bar"><span class="nm">{_avatar(himg.get(hero), "baravatar", hero)}{esc(hero)}</span>'
                 f'<span class="track"><span class="fill" style="width:{w}%;background:{grad}"></span></span>'
                 f'<span class="val">{c(v)}</span></div>')
    return rows


def self_damage_panel(me):
    sd = me.get("self_damage", 0)
    heal = me.get("self_heal", 0)
    bd = me.get("self_damage_breakdown") or []
    if not (sd or heal or bd):
        return ""
    rows = "".join(f'<span class="sdrow"><span class="sn">{esc(b["name"])}</span>'
                   f'<span class="sv">{c(b["amount"])}</span></span>' for b in bd[:6])
    healnote = f' &nbsp;·&nbsp; self-heal / regen <b>{c(heal)}</b>' if heal else ""
    return (f'<div class="sdpanel">'
            f'<div class="sdhead"><span class="k">Self-damage</span> <span class="v">{c(sd)}</span> '
            f'<span class="sdsub">excludes regen{healnote}</span></div>'
            f'<div class="sdlist">{rows}</div>'
            f'<div class="note">Passive items (e.g. Blood Tribute) show here as their HP cost only — '
            f'their bonus power and regen are baked into your other damage, so this cost is not wasted output.</div>'
            f'</div>')


def targeting_section(digest, me, analysis, item_index):
    tgt = (analysis or {}).get("targeting_overall", "")
    tgt_html = (f'<div class="verdict">{rich(tgt, digest)}</div>' if tgt
                else '<div class="verdict pending">Analysis pending.</div>')
    himg = {p["hero"]: p.get("hero_image") for p in digest["players"] if p.get("hero")}
    dealt = me.get("damage_dealt_to", {})
    taken = me.get("damage_taken_from", {})
    self_chip = self_damage_panel(me)

    # focus enemy cards
    by_hero = {p["hero"]: p for p in digest["players"]}
    fen = (analysis or {}).get("focus_enemy_notes", {})
    cards = ""
    for hero in digest.get("focus_enemies", []):
        p = by_hero.get(hero, {})
        ko = p.get("kills_on_me", 0)
        note = fen.get(hero, "")
        ksub = f"Killed you {ko}×" if ko else "Key threat"
        ntxt = rich(note, digest) if note else '<span class="pending">Analysis pending.</span>'
        cards += (f'<div class="ecard"><div class="h">{_avatar(p.get("hero_image"), "hava", hero)}{esc(hero)}</div>'
                  f'<div class="k">{ksub}</div><div class="t">{ntxt}</div></div>')
    cards_html = (f'<div class="subhead">The enemies who beat you</div>'
                  f'<div class="cards3">{cards}</div>') if cards else ""

    # remedies: unique item suggestions aggregated across phases
    seen, rem = set(), []
    for ph in PHASES:
        for s in ((analysis or {}).get("phases", {}).get(ph, {}) or {}).get("item_suggestions", []) or []:
            name = s.get("item")
            if name and name not in seen:
                seen.add(name); rem.append(s)
    rem_html = ""
    if rem:
        rem_html = suggestion_chips(rem, item_index, label="The remedies you skipped", size=38)
        rem_html += ('<div class="note">Item icons resolve to live Deadlock art from '
                     'assets.deadlock-api.com when the report is generated.</div>')

    return f'''<section id="targeting" class="divided">
      {sec_head("Targeting & threats")}
      <div class="bracket" style="padding:20px 22px">{brackets()}{tgt_html}
        <div class="tgt-grid">
          <div><div class="tgt-h good">You dealt damage to</div>{dmg_bars(dealt, "good", himg)}</div>
          <div><div class="tgt-h bad">You took damage from</div>{dmg_bars(taken, "bad", himg)}</div>
        </div>
        {self_chip}
      </div>
      {cards_html}
      {rem_html}
    </section>'''


# ---- scoreboard -------------------------------------------------------------
def scoreboard(digest):
    rows = ""
    for t in (digest["my_team"], 1 - digest["my_team"]):
        ps = sorted([p for p in digest["players"] if p["team"] == t], key=lambda x: -x["net_worth"])
        won = bool(ps and ps[0]["won"])
        cls = "won" if won else "lost"
        rows += (f'<tr class="teamhead {cls}"><td colspan="7">Team {t} — '
                 f'{"Won" if won else "Lost"}</td></tr>')
        for p in ps:
            sp = p["split"]
            kk, dd, aa = p["kda"]
            you = p["is_me"]
            tag = ('<span class="youtag">You</span>' if you
                   else (f'<span class="kotag">killed you {p["kills_on_me"]}×</span>'
                         if p.get("kills_on_me") else ""))
            rowcls = "row you" if you else "row"
            split = (f'<span class="wsv"><span class="w">W{sp["weapon"]}</span> '
                     f'<span class="s">S{sp["spirit"]}</span> '
                     f'<span class="v">V{sp["vitality"]}</span></span>')
            rows += (f'<tr class="{rowcls}">'
                     f'<td class="name">{_avatar(p.get("hero_image"), "sbava", p["hero"])}{esc(p["hero"])}{tag}</td>'
                     f'<td class="kda">{kk}/{dd}/{aa}</td>'
                     f'<td class="nw">{c(p["net_worth"])}</td>'
                     f'<td class="r mut">{c(p["souls_per_min"])}</td>'
                     f'<td class="r mut">{p["last_hits"]}/{p["denies"]}</td>'
                     f'<td>{split}</td>'
                     f'<td class="r mut">{p["level"]}</td></tr>')
    return f'''<section id="scoreboard" class="divided">
      {sec_head("Scoreboard")}
      <div class="sbwrap"><table class="sb">
        <thead><tr>
          <th>Hero</th><th>K/D/A</th><th class="r">Net worth</th><th class="r">Souls/min</th>
          <th class="r">LH/DN</th><th>Items (W/S/V)</th><th class="r">Lvl</th>
        </tr></thead>
        <tbody>{rows}</tbody>
      </table></div>
    </section>'''


# ---- builds -----------------------------------------------------------------
def build_row(p):
    items = p.get("final_build_items") or []
    if not items:
        return '<p class="pending">No build data available.</p>'
    cards = "".join(item_card(it["id"], it["name"]) for it in items if it.get("id"))
    return f'<div class="buildrow">{cards}</div>'


def builds_section(digest):
    players = digest["players"]
    me = next(p for p in players if p["is_me"])
    my_team = me["team"]
    focus = set(digest.get("focus_enemies") or [])
    enemies = sorted([p for p in players if p["team"] != my_team],
                     key=lambda x: (-(x.get("kills_on_me") or 0), -x["net_worth"]))
    # who beat you: enemies who killed you, else the flagged focus enemies, else top 3 by net worth
    beat = ([p for p in enemies if (p.get("kills_on_me") or 0) > 0]
            or [p for p in enemies if p["hero"] in focus]
            or enemies[:3])
    enemy_html = ""
    for p in beat:
        kk, dd, aa = p["kda"]
        ko = p.get("kills_on_me") or 0
        kotag = f'<span class="kotag">killed you {ko}×</span>' if ko else ""
        summ = (f'{_avatar(p.get("hero_image"), "hava", p["hero"])}{esc(p["hero"])} &nbsp;·&nbsp; '
                f'{kk}/{dd}/{aa} &nbsp;·&nbsp; {c(p["net_worth"])} souls{kotag}')
        enemy_html += (f'<details class="cat"><summary class="cat-h">'
                       f'<span class="dia">◆</span>{summ}</summary>'
                       f'<div class="cat-b">{build_row(p)}</div></details>')
    return f'''<section id="builds" class="divided">
      {sec_head("Builds")}
      <div class="bracket">{brackets()}
        <div class="subhead" style="margin-top:0">Your final build</div>
        {build_row(me)}
        <div class="note">Hover any item for its tooltip.</div>
      </div>
      <div class="subhead">The builds that beat you</div>
      {enemy_html}
    </section>'''


# ---- hero playbook (situational tips, macro, learn-more resources) ----------
def resource_link(r, digest):
    url = r.get("url", "")
    try:
        host = urlsplit(url).netloc.replace("www.", "")
    except Exception:
        host = ""
    kind = (r.get("kind") or "link").lower()
    badge = {"video": "▶ Video", "article": "❖ Article"}.get(kind, "↗ Link")
    return (f'<a class="res" href="{esc(url)}" target="_blank" rel="noopener noreferrer">'
            f'<span class="rk">{badge}</span>'
            f'<span class="rt">{esc(r.get("title", ""))}</span>'
            f'<span class="rwhy">{rich(r.get("why", ""), digest)}</span>'
            f'<span class="rhost">{esc(host)}</span></a>')


def playbook_section(digest, analysis):
    a = analysis or {}
    hg = a.get("hero_guide") or {}
    overview = hg.get("overview", "")
    situations = hg.get("situations") or []
    macro = a.get("macro_tips") or []
    resources = a.get("resources") or []
    if not (overview or situations or macro or resources):
        return ""
    me = next(p for p in digest["players"] if p["is_me"])
    parts = []
    if overview:
        parts.append(f'<div class="bracket">{brackets()}<div class="verdict">{rich(overview, digest)}</div></div>')
    if situations:
        cards = "".join(
            f'<div class="sitcard"><div class="sit-h">{rich(s.get("situation", ""), digest)}</div>'
            f'<div class="sit-b">{rich(s.get("advice", ""), digest)}</div></div>'
            for s in situations)
        parts.append(f'<div class="subhead">Situational play</div><div class="sitgrid">{cards}</div>')
    if macro:
        lis = "".join(f'<li>{rich(m, digest)}</li>' for m in macro)
        parts.append(f'<div class="subhead">Macro: turning fights into objectives</div><ul class="tips">{lis}</ul>')
    if resources:
        rows = "".join(resource_link(r, digest) for r in resources)
        parts.append(f'<div class="subhead">Go deeper</div><div class="reslist">{rows}</div>'
                     '<div class="note">External guides — open in a new tab.</div>')
    return f'''<section id="playbook" class="divided">
      {sec_head(me["hero"] + " playbook")}
      {"".join(parts)}
    </section>'''


# ---- deaths map + timeline --------------------------------------------------
# Calibration of world (x, y) -> minimap image position. The play area spans +/- radius about the
# map origin; flip these if markers come out mirrored when checked against the map image.
MAP_FLIP_X = False
MAP_FLIP_Y = False  # world +y is north -> top of image (top% small)


def coord_to_pct(x, y, radius):
    r = radius or 10752
    fx = -x if MAP_FLIP_X else x
    fy = -y if MAP_FLIP_Y else y
    left = (fx + r) / (2 * r) * 100        # -r -> 0% (left), +r -> 100% (right)
    top = (r - fy) / (2 * r) * 100         # +r -> 0% (top), -r -> 100% (bottom)
    return max(0, min(100, left)), max(0, min(100, top))


ASSET_MINIMAP = Path(__file__).resolve().parent.parent / "assets" / "minimap.png"


def _map_image_src(digest):
    """Prefer the bundled minimap (embedded as a data URI so reports are self-contained and work on
    the live site); fall back to the deadlock-api map URL."""
    try:
        if ASSET_MINIMAP.exists():
            import base64
            b64 = base64.b64encode(ASSET_MINIMAP.read_bytes()).decode()
            return f"data:image/png;base64,{b64}"
    except Exception:
        pass
    return (digest.get("map") or {}).get("image")


def death_map(digest):
    mp = digest.get("map") or {}
    img = _map_image_src(digest)
    R = mp.get("radius") or 10752
    if not img:
        return ""
    me = next(p for p in digest["players"] if p["is_me"])
    deaths = [d for d in (me.get("deaths") or []) if d.get("pos")]
    kills = [d for d in (me.get("kills") or []) if d.get("pos")]
    lines, markers = "", ""
    for i, d in enumerate(deaths, 1):
        dl, dt = coord_to_pct(d["pos"][0], d["pos"][1], R)
        if d.get("killer_pos"):
            kl, kt = coord_to_pct(d["killer_pos"][0], d["killer_pos"][1], R)
            lines += f'<line x1="{kl:.2f}" y1="{kt:.2f}" x2="{dl:.2f}" y2="{dt:.2f}"/>'
        title = (f'#{i} · {d["t"]} ({d["phase"]}) — killed by {d["killer"]}; '
                 f'focused {d["focused_s"]}s, {d.get("down_s")}s dead')
        markers += (f'<div class="dmark death" style="left:{dl:.2f}%;top:{dt:.2f}%" '
                    f'title="{esc(title)}">{i}</div>')
    for d in kills:
        kl, kt = coord_to_pct(d["pos"][0], d["pos"][1], R)
        ktitle = esc("Kill · {} — {}".format(d["t"], d["victim"]))
        markers += (f'<div class="dmark kill" style="left:{kl:.2f}%;top:{kt:.2f}%" '
                    f'title="{ktitle}"></div>')
    svg = f'<svg class="ganksvg" viewBox="0 0 100 100" preserveAspectRatio="none">{lines}</svg>'
    legend = ('<div class="maplegend"><span class="lg death">your deaths</span>'
              '<span class="lg kill">your kills</span>'
              '<span class="lg line">killer → you</span></div>')
    return (f'<div class="mapwrap"><img class="mapimg" src="{esc(img)}" alt="map">'
            f'{svg}<div class="mlayer">{markers}</div></div>{legend}')


def death_timeline(digest):
    me = next(p for p in digest["players"] if p["is_me"])
    deaths = me.get("deaths") or []
    if not deaths:
        return '<p class="pending">No deaths recorded.</p>'
    himg = {p["hero"]: p.get("hero_image") for p in digest["players"] if p.get("hero")}
    cards = ""
    for i, d in enumerate(deaths, 1):
        killer = d["killer"]
        dw = d.get("dmg_window") or {}
        srcs = "".join(f'<span class="dsrc">{_avatar(himg.get(h), "ava", h)}{esc(h)} {c(v)}</span>'
                       for h, v in list(dw.items())[:4])
        dmg = f'<div class="dtl-dmg"><span class="dlabel">damage to you</span>{srcs}</div>' if srcs else ""
        loc = f' · pos {d["pos"][0]}, {d["pos"][1]}' if d.get("pos") else ""
        cards += (f'<div class="dtl-card"><div class="dtl-n">{i}</div><div class="dtl-main">'
                  f'<div class="dtl-h">{_avatar(himg.get(killer), "hava", killer)}'
                  f'<b>{esc(killer)}</b> killed you'
                  f'<span class="dtl-t">{esc(d["t"])} · {esc(d["phase"])}</span></div>'
                  f'<div class="dtl-meta">focused {d["focused_s"]}s · {d.get("down_s")}s dead{loc}</div>'
                  f'{dmg}</div></div>')
    return f'<div class="dtl">{cards}</div>'


def deaths_section(digest):
    me = next(p for p in digest["players"] if p["is_me"])
    if not (me.get("deaths") or me.get("kills")):
        return ""
    return f'''<section id="deaths" class="divided">
      {sec_head("Deaths & map")}
      <div class="bracket">{brackets()}{death_map(digest)}</div>
      <div class="subhead">Death timeline</div>
      {death_timeline(digest)}
      <div class="note">Marker numbers match the timeline. The killer is exact; "damage to you" is the
      cumulative damage-matrix window bracketing each death (~3-min samples), so it is approximate.</div>
    </section>'''


# ---- assembly ---------------------------------------------------------------
def nav_links():
    items = ["Overview", "Charts"] + PHASES + ["Builds", "Targeting", "Deaths", "Playbook", "Scoreboard"]
    return "".join(f'<a href="#{s.lower().replace(" ", "-")}">{esc(s)}</a>' for s in items)


def header(digest, me):
    result = "Victory" if digest["i_won"] else "Defeat"
    rcls = "win" if digest["i_won"] else "loss"
    kk, dd, aa = me["kda"]
    return f'''<header class="site"><div class="hwrap">
      <a class="homelink" href="../">&#8592; All matches</a>
      <div class="hrow">
        <div class="heroname brass-text">{esc(me["hero"])}</div>
        <span class="result {rcls}">◆ {esc(result)}</span>
        <span class="metaline">{esc(digest["duration"])} &nbsp;·&nbsp; {kk} / {dd} / {aa} &nbsp;·&nbsp;
          <span class="souls">{c(me["net_worth"])} souls</span> &nbsp;·&nbsp;
          <span class="mid">match {esc(digest["match_id"])}</span></span>
      </div>
      <nav>{nav_links()}</nav>
    </div></header>'''


def build(digest, analysis):
    ch = C.build_all_charts(digest)
    me = next(p for p in digest["players"] if p["is_me"])
    item_index = digest.get("item_index", {})
    phases = "".join(phase_section(p, digest, analysis, item_index)
                     for p in PHASES if p in me.get("phases", {}))
    return f'''<!doctype html><html><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Deadlock match {esc(digest["match_id"])} — {esc(me["hero"])} report</title>
<meta name="robots" content="noindex, nofollow">
<meta name="googlebot" content="noindex, nofollow">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Big+Shoulders+Display:wght@400;500;600;700;800;900&family=Barlow:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Barlow+Semi+Condensed:wght@500;600;700&display=swap" rel="stylesheet">
<script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
<script type="module" src="https://unpkg.com/@deadlock-api/ui-core/dist/main/main.esm.js"></script>
<style>{CSS}</style></head>
<body>
<dl-provider language="english" show-tier-badge="true">
<div class="tex"></div><div class="vig"></div>
{header(digest, me)}
<main>
{overview(digest, me, analysis)}
{charts_section(ch)}
{phases}
{builds_section(digest)}
{targeting_section(digest, me, analysis, item_index)}
{deaths_section(digest)}
{playbook_section(digest, analysis)}
{scoreboard(digest)}
<div class="footer">Generated by <b>deadlock-match-report</b> · data via deadlock-api.com · portraits, item icons &amp; cards via assets.deadlock-api.com</div>
</main>
</dl-provider>
</body></html>'''


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--digest", required=True)
    ap.add_argument("--analysis")
    ap.add_argument("--out")
    a = ap.parse_args()
    digest = json.loads(Path(a.digest).read_text())
    analysis = json.loads(Path(a.analysis).read_text()) if a.analysis and Path(a.analysis).exists() else None
    out = a.out or f'{digest["match_id"]}_report.html'
    Path(out).write_text(build(digest, analysis))
    print("wrote", out)
